// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {facade} from '../models';

export function DeleteCategoryFromFrontend(arg1:string):Promise<Array<domain.Category>>;

export function LoadCategories():Promise<Array<domain.Category>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveCategories(arg1:Array<domain.Category>):Promise<void>;

export function SaveCategoryFromFrontend(arg1:facade.CategoryForm):Promise<Array<domain.Category>>;
