// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCategoryFromFrontend(arg1) {
  return window['go']['facade']['CategoryFacade']['DeleteCategoryFromFrontend'](arg1);
}

export function LoadCategories() {
  return window['go']['facade']['CategoryFacade']['LoadCategories']();
}

export function RegisterEvents(arg1) {
  return window['go']['facade']['CategoryFacade']['RegisterEvents'](arg1);
}

export function SaveCategories(arg1) {
  return window['go']['facade']['CategoryFacade']['SaveCategories'](arg1);
}

export function SaveCategoryFromFrontend(arg1) {
  return window['go']['facade']['CategoryFacade']['SaveCategoryFromFrontend'](arg1);
}
