// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {facade} from '../models';

export function DeleteLinkFromFrontend(arg1:string):Promise<Array<domain.Link>>;

export function LoadLinks():Promise<Array<domain.Link>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveLinkFromFrontend(arg1:facade.LinkForm):Promise<Array<domain.Link>>;

export function SaveLinks(arg1:Array<domain.Link>):Promise<void>;
