// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLinkFromFrontend(arg1) {
  return window['go']['facade']['LinkFacade']['DeleteLinkFromFrontend'](arg1);
}

export function LoadLinks() {
  return window['go']['facade']['LinkFacade']['LoadLinks']();
}

export function RegisterEvents(arg1) {
  return window['go']['facade']['LinkFacade']['RegisterEvents'](arg1);
}

export function SaveLinkFromFrontend(arg1) {
  return window['go']['facade']['LinkFacade']['SaveLinkFromFrontend'](arg1);
}

export function SaveLinks(arg1) {
  return window['go']['facade']['LinkFacade']['SaveLinks'](arg1);
}
