// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function DeleteMemoFromFrontend(arg1:string):Promise<domain.MemoDashboardDTO>;

export function DeleteMemoTagFromFrontend(arg1:string):Promise<domain.MemoDashboardDTO>;

export function GetMemoStats():Promise<domain.MemoStats>;

export function LoadMemos():Promise<Array<domain.Memo>>;

export function LoadMemosFromFrontend():Promise<domain.MemoDashboardDTO>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function RenameMemoTagFromFrontend(arg1:string,arg2:string):Promise<domain.MemoDashboardDTO>;

export function SaveMemoFromFrontend(arg1:string):Promise<domain.MemoDashboardDTO>;

export function SaveMemos(arg1:Array<domain.Memo>):Promise<void>;

export function UpdateMemoFromFrontend(arg1:domain.Memo):Promise<domain.MemoDashboardDTO>;
