// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMemoFromFrontend(arg1) {
  return window['go']['facade']['MemoFacade']['DeleteMemoFromFrontend'](arg1);
}

export function DeleteMemoTagFromFrontend(arg1) {
  return window['go']['facade']['MemoFacade']['DeleteMemoTagFromFrontend'](arg1);
}

export function GetMemoStats() {
  return window['go']['facade']['MemoFacade']['GetMemoStats']();
}

export function LoadMemos() {
  return window['go']['facade']['MemoFacade']['LoadMemos']();
}

export function LoadMemosFromFrontend() {
  return window['go']['facade']['MemoFacade']['LoadMemosFromFrontend']();
}

export function RegisterEvents(arg1) {
  return window['go']['facade']['MemoFacade']['RegisterEvents'](arg1);
}

export function RenameMemoTagFromFrontend(arg1, arg2) {
  return window['go']['facade']['MemoFacade']['RenameMemoTagFromFrontend'](arg1, arg2);
}

export function SaveMemoFromFrontend(arg1) {
  return window['go']['facade']['MemoFacade']['SaveMemoFromFrontend'](arg1);
}

export function SaveMemos(arg1) {
  return window['go']['facade']['MemoFacade']['SaveMemos'](arg1);
}

export function UpdateMemoFromFrontend(arg1) {
  return window['go']['facade']['MemoFacade']['UpdateMemoFromFrontend'](arg1);
}
