// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {facade} from '../models';

export function DeleteMenuFromFrontend(arg1:number):Promise<Array<domain.Menu>>;

export function LoadMenus():Promise<Array<domain.Menu>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveMenuFromFrontend(arg1:facade.MenuForm):Promise<Array<domain.Menu>>;

export function SaveMenus(arg1:Array<domain.Menu>):Promise<void>;
