// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllStatuses() {
  return window['go']['facade']['OAuthFacade']['GetAllStatuses']();
}

export function HasCredential(arg1, arg2) {
  return window['go']['facade']['OAuthFacade']['HasCredential'](arg1, arg2);
}

export function IsOAuthAvailable(arg1) {
  return window['go']['facade']['OAuthFacade']['IsOAuthAvailable'](arg1);
}

export function OAuthSupportedProviders() {
  return window['go']['facade']['OAuthFacade']['OAuthSupportedProviders']();
}

export function RevokeToken(arg1) {
  return window['go']['facade']['OAuthFacade']['RevokeToken'](arg1);
}

export function StartOAuthFlow(arg1) {
  return window['go']['facade']['OAuthFacade']['StartOAuthFlow'](arg1);
}
