// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetAllStatuses():Promise<Record<string, service.PlatformStatus>>;

export function HasCredential(arg1:string,arg2:string):Promise<boolean>;

export function IsOAuthAvailable(arg1:string):Promise<boolean>;

export function OAuthSupportedProviders():Promise<Array<string>>;

export function RevokeToken(arg1:string):Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<void>;
