// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePost(arg1) {
  return window['go']['facade']['PostFacade']['DeletePost'](arg1);
}

export function DeletePostFromFrontend(arg1) {
  return window['go']['facade']['PostFacade']['DeletePostFromFrontend'](arg1);
}

export function LoadPosts() {
  return window['go']['facade']['PostFacade']['LoadPosts']();
}

export function LoadTags() {
  return window['go']['facade']['PostFacade']['LoadTags']();
}

export function SavePost(arg1) {
  return window['go']['facade']['PostFacade']['SavePost'](arg1);
}

export function SavePostFromFrontend(arg1) {
  return window['go']['facade']['PostFacade']['SavePostFromFrontend'](arg1);
}

export function UploadImages(arg1) {
  return window['go']['facade']['PostFacade']['UploadImages'](arg1);
}

export function UploadImagesFromFrontend(arg1) {
  return window['go']['facade']['PostFacade']['UploadImagesFromFrontend'](arg1);
}
