// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {facade} from '../models';

export function DeletePost(arg1:string):Promise<void>;

export function DeletePostFromFrontend(arg1:string):Promise<Array<domain.Post>>;

export function LoadPosts():Promise<Array<domain.Post>>;

export function LoadTags():Promise<Array<domain.Tag>>;

export function SavePost(arg1:domain.PostInput):Promise<void>;

export function SavePostFromFrontend(arg1:domain.PostInput):Promise<facade.PostDashboardDTO>;

export function UploadImages(arg1:Array<domain.UploadedFile>):Promise<Array<string>>;

export function UploadImagesFromFrontend(arg1:Array<domain.UploadedFile>):Promise<Array<string>>;
