// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort() {
  return window['go']['facade']['PreviewFacade']['GetPort']();
}

export function GetPreviewURL() {
  return window['go']['facade']['PreviewFacade']['GetPreviewURL']();
}

export function IsRunning() {
  return window['go']['facade']['PreviewFacade']['IsRunning']();
}

export function SetBuildDir(arg1) {
  return window['go']['facade']['PreviewFacade']['SetBuildDir'](arg1);
}

export function SetContext(arg1) {
  return window['go']['facade']['PreviewFacade']['SetContext'](arg1);
}

export function StartPreviewServer() {
  return window['go']['facade']['PreviewFacade']['StartPreviewServer']();
}

export function StopPreviewServer() {
  return window['go']['facade']['PreviewFacade']['StopPreviewServer']();
}
