// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetPort():Promise<number>;

export function GetPreviewURL():Promise<string>;

export function IsRunning():Promise<boolean>;

export function SetBuildDir(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartPreviewServer():Promise<string>;

export function StopPreviewServer():Promise<void>;
