// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting() {
  return window['go']['facade']['SettingFacade']['GetSetting']();
}

export function RemoteDetectFromFrontend(arg1) {
  return window['go']['facade']['SettingFacade']['RemoteDetectFromFrontend'](arg1);
}

export function SaveAvatar(arg1) {
  return window['go']['facade']['SettingFacade']['SaveAvatar'](arg1);
}

export function SaveFavicon(arg1) {
  return window['go']['facade']['SettingFacade']['SaveFavicon'](arg1);
}

export function SaveSettingFromFrontend(arg1) {
  return window['go']['facade']['SettingFacade']['SaveSettingFromFrontend'](arg1);
}
