// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {facade} from '../models';

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteTagFromFrontend(arg1:string):Promise<Array<domain.Tag>>;

export function GetTagColors():Promise<Array<string>>;

export function LoadTags():Promise<Array<domain.Tag>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveTag(arg1:domain.Tag,arg2:string):Promise<void>;

export function SaveTagFromFrontend(arg1:facade.TagForm):Promise<Array<domain.Tag>>;
