// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSite(arg1, arg2) {
  return window['go']['app']['App']['AddSite'](arg1, arg2);
}

export function GetPreviewURL() {
  return window['go']['app']['App']['GetPreviewURL']();
}

export function GetSites() {
  return window['go']['app']['App']['GetSites']();
}

export function RemoveSite(arg1) {
  return window['go']['app']['App']['RemoveSite'](arg1);
}

export function SwitchSite(arg1) {
  return window['go']['app']['App']['SwitchSite'](arg1);
}

export function UpdateSites(arg1) {
  return window['go']['app']['App']['UpdateSites'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function LoadSite() {
  return window['go']['app']['App']['LoadSite']();
}

export function OpenFolderDialog() {
  return window['go']['app']['App']['OpenFolderDialog']();
}

export function OpenImageDialog() {
  return window['go']['app']['App']['OpenImageDialog']();
}

export function OpenKeyFileDialog() {
  return window['go']['app']['App']['OpenKeyFileDialog']();
}

export function ShowPreferences() {
  return window['go']['app']['App']['ShowPreferences']();
}

export function ShowToast(arg1, arg2) {
  return window['go']['app']['App']['ShowToast'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
