// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context,config} from '../models';

export function AddSite(arg1:string,arg2:string):Promise<Array<config.SiteEntry>>;

export function GetPreviewURL():Promise<string>;

export function GetSites():Promise<Array<config.SiteEntry>>;

export function RemoveSite(arg1:string):Promise<Array<config.SiteEntry>>;

export function SwitchSite(arg1:string):Promise<void>;

export function UpdateSites(arg1:Array<config.SiteEntry>):Promise<void>;

export function GetVersion():Promise<string>;

export function LoadSite():Promise<Record<string, any>>;

export function OpenFolderDialog():Promise<Array<string>>;

export function OpenImageDialog():Promise<string>;

export function OpenKeyFileDialog():Promise<string>;

export function ShowPreferences():Promise<void>;

export function ShowToast(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
