// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function DeleteCategory(arg1:string):Promise<void>;

export function LoadCategories():Promise<Array<domain.Category>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveCategories(arg1:Array<domain.Category>):Promise<void>;

export function SaveCategory(arg1:domain.Category,arg2:string):Promise<void>;
