// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteComment(arg1) {
  return window['go']['facade']['CommentFacade']['DeleteComment'](arg1);
}

export function FetchComments(arg1, arg2) {
  return window['go']['facade']['CommentFacade']['FetchComments'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['facade']['CommentFacade']['GetSettings']();
}

export function ReplyComment(arg1, arg2, arg3) {
  return window['go']['facade']['CommentFacade']['ReplyComment'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['facade']['CommentFacade']['SaveSettings'](arg1);
}
