// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteComment(arg1:string):Promise<void>;

export function FetchComments(arg1:number,arg2:number):Promise<domain.PaginatedComments>;

export function GetSettings():Promise<domain.CommentSettings>;

export function ReplyComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:domain.CommentSettings):Promise<void>;
