// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function LoadMenus():Promise<Array<domain.Menu>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SaveMenus(arg1:Array<domain.Menu>):Promise<void>;
