// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadMenus() {
  return window['go']['facade']['MenuFacade']['LoadMenus']();
}

export function RegisterEvents(arg1) {
  return window['go']['facade']['MenuFacade']['RegisterEvents'](arg1);
}

export function SaveMenus(arg1) {
  return window['go']['facade']['MenuFacade']['SaveMenus'](arg1);
}
