// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function DeletePost(arg1:string):Promise<void>;

export function LoadPosts():Promise<Array<domain.Post>>;

export function LoadTags():Promise<Array<domain.Tag>>;

export function RegisterEvents(arg1:context.Context):Promise<void>;

export function SavePost(arg1:domain.PostInput):Promise<void>;

export function UploadImages(arg1:Array<domain.UploadedFile>):Promise<Array<string>>;
