// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterEvents(arg1) {
  return window['go']['facade']['RendererFacade']['RegisterEvents'](arg1);
}

export function RenderAll() {
  return window['go']['facade']['RendererFacade']['RenderAll']();
}
