// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetSetting():Promise<domain.Setting>;

export function SaveAvatar(arg1:string):Promise<void>;

export function SaveFavicon(arg1:string):Promise<void>;
