// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTag(arg1) {
  return window['go']['facade']['TagFacade']['DeleteTag'](arg1);
}

export function LoadTags() {
  return window['go']['facade']['TagFacade']['LoadTags']();
}

export function RegisterEvents(arg1) {
  return window['go']['facade']['TagFacade']['RegisterEvents'](arg1);
}

export function SaveTag(arg1, arg2) {
  return window['go']['facade']['TagFacade']['SaveTag'](arg1, arg2);
}
