// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {facade} from '../models';

export function LoadThemeConfig():Promise<domain.ThemeConfig>;

export function LoadThemes():Promise<Array<domain.Theme>>;

export function RegisterEvents(arg1:context.Context,arg2:facade.RendererFacade):Promise<void>;

export function SaveThemeConfig(arg1:domain.ThemeConfig):Promise<void>;
