// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadThemeConfig() {
  return window['go']['facade']['ThemeFacade']['LoadThemeConfig']();
}

export function LoadThemes() {
  return window['go']['facade']['ThemeFacade']['LoadThemes']();
}

export function RegisterEvents(arg1, arg2) {
  return window['go']['facade']['ThemeFacade']['RegisterEvents'](arg1, arg2);
}

export function SaveThemeConfig(arg1) {
  return window['go']['facade']['ThemeFacade']['SaveThemeConfig'](arg1);
}
