// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSite() {
  return window['go']['main']['App']['LoadSite']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}
