// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSite():Promise<main.SiteData>;

export function OpenFolderDialog():Promise<Array<string>>;
